<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" conetent="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php
		$_SESSION['pages']="tc.php";
		$page_title="information";
		include("menu.php");
	?>
	<script>
		// When the user scrolls down 20px from the top of the document, show the button
		window.onscroll = function() {scrollFunction()};

		function scrollFunction() {
		    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
		        document.getElementById("topBtn").style.display = "block";
		    } else {
		        document.getElementById("topBtn").style.display = "none";
		    }
		}

		// When the user clicks on the button, scroll to the top of the document
		function topFunction() {
		    document.body.scrollTop = 0; // For Safari
		    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
		}
	</script>
	<title>Terms of Use Agreement - SabahTCM</title>	
</head>
<body>
	<div id="breadcrum">
		<a href="index.php"><i class="icon-home icon-large"></i>&nbsp;Home</a>&nbsp;&nbsp;>
		<a href="tc.php"><i class="icon-question icon-large"></i>&nbsp;Terms of Use Agreement</a>&nbsp;&nbsp;
	</div>
	</br>
	<button onclick="topFunction()" id="topBtn" title="Go to top">Top</button>
	<div id="body">
		<div class="content" style="text-align:justify;">	
			<h4>Terms of Use Agreement</h4>
			<b>Table of Contents</b>
			
			<ol><li><a href='#purpose'>Purpose</a></li>
				<li><a href='#advice'>Not Healthcare Advice</a></li>
				<li><a href='#author'>Authority</a></li>
				<li><a href='#usage'>Site Usage & Usage Termination</a></li>
				<li><a href='#user'>User Content and Conduct</a></li>
				<li><a href='#privacy'>Privacy Policy</a></li>
				<li><a href='#disclaimer'>Liability Disclaimer</a></li>
				<li><a href='#indem'>Indemnification</a></li>
				<li><a href='#cr'>Copyright, Trademarks and other Intellectual Property</a></li>
				<li><a href='#agree'>Agreement</a></li>
				<li><a href='#sever'>Severability; Interpretation</a></li>
				<li><a href='#mis'>Miscellaneous</a></li>
				<li><a href='#cu'>Contact Us</a></li>
			</ol>
			<hr>

			<ol><b><li id='purpose'>Purpose</li></b>
				<p>Welcome to SabahTCM websites (the "Site"). This SabahTCM Terms of Use Agreement ("Agreement") sets forth the agreement between SabahTCM, and SabahTCM developers (together "We", "Us", or "Our”), and each admin ("Admin"), and each user ("User", "Your" or "You") governing the use by you of the Site, and the SabahTCM Privacy Policy (“Privacy Policy”). Please read this agreement carefully and fully before using the Site, or disclosing to us any personal information.</p>
				<p>By using the Site, or disclosing to us any personal information: (i) you agree that you have read and understand the terms of this Agreement, (ii) you accept and agree to be bound by the terms of this Agreement, and (iii) you accept and agree to abide by all laws and regulations applicable to the subject matter of this Agreement.</p>
				<p>IF YOU DO NOT AGREE TO THE TERMS OF THIS AGREEMENT, DO NOT ACCESS OR OTHERWISE USE THE SITE, OR DISCLOSE TO US ANY PERSONAL INFORMATION.</p>
				<p>The terms of use contained in this Agreement may change periodically and may be revised at any time and from time to time in our sole discretion by updating this posting. You should visit this page from time to time to review the then current terms of use because they are binding on you. Your continued use of the Site means that you accept any changes or modifications to this Agreement. If any modification is unacceptable to you, your only recourse is to terminate this Agreement by <a href="about.php">Contact Us</a>. Certain provisions of the terms of use contained in this Agreement may be superseded by legal notices or terms located on particular pages of the Site.</p></br>

				<b><li id='advice'>Not Healthcare Advice</li></b>
				<p>Information and other content provided on the Site, including information that may be provided on the Site directly or by linking to third-party websites are provided for informational purposes only. Please consult with a physician or other healthcare professional regarding any medical or health related diagnosis or treatment options.</p>
				<p>Information provided on the Site and linked websites, including information relating to medical and health conditions, treatments and herbal may be provided in summary form. Information on the Site should not be considered as a substitute for advice from a healthcare professional. The Site does not recommend self-management of health issues. Information on the Site is not comprehensive and does not cover all diseases, ailments, physical conditions or their treatment. Contact your healthcare professional promptly should you have any health related questions. Never disregard or delay medical advice based upon information you may have read on the Site.</p>
				<p>Links to or access from any third party websites or resources is not an endorsement of any information. We are not responsible for the content or performance of any third party websites. Use of any third party websites is at your own risk.</p>
				<p>You should not use the information on the Site to diagnose or treat any health issues or for prescription of any medication or other treatment. You should always consult with your healthcare professional and read information provided, prior to using any medication, or herbal, or before beginning any treatment for a health issue. Individuals are different and may react differently to different herbal. You should consult your physician about interactions between medications you are taking. Comments made in any forums on the Site by admin or Site users are strictly their own personal views made in their own personal capacity and are not claims made by us or do they represent the our positions or views.</p>
				<p>We are not liable for any information provided on the Site with regard to recommendations regarding herbal for any health purposes. Herbal are not intended to treat, prevent or cure disease. Consult with a healthcare professional before starting any treatment. We are not responsible for any issues that trigger from the information provided even if we have been advised of the possibility of issues.</p></br>

				<b><li id='author'>Authority</li></b>
				<p>By using our Site, you represent and agree that you are at least 18 years of age or older and are fully able and competent to enter into the terms, conditions, representations and warranties set forth in this Agreement; otherwise, please exit the Site. The Site is not intended or designed to attract users under the age of 18. We do not collect personal information from any person we know to be under the age of 18. If you are under the age of 18, you are not permitted to disclose or send to us any personal information.</p>
				<p>The Site is operated for the Final Year Project (FYP) Universiti Malaysia Sabah (UMS) Malaysia purpose only. All the personal information sent to us is governed by the privacy policies of the Sabah. We make no representation that the Site or its content (including, without limitation, any herbal available on or through the Site) are appropriate or available for use in other locations. If you access the Site from outside the Sabah of Malaysia you do so on your own initiative and must bear all responsibility for compliance with applicable local laws. You agree you will not use the Site content or products in any country or in any manner prohibited by any applicable laws, restrictions or regulations. Users from the other countries are advised not to disclose personal information to us unless you consent to the application of Sabah law and to the use and disclosure of your information consistent with our Privacy Policy.</p></br>

				<b><li id='usage'>Site Usage & Usage Termination</li></b>
				<p>You are required to establish an account on the Site in order to use certain features, such as forum. You agree to provide accurate, true, complete and current information about yourself as prompted by the Site and to promptly update such information to maintain accurate, true, complete and current information. If you provide any inaccurate, false, incomplete or outdated information or we in our sole discretion suspect that such information is inaccurate, false, incomplete or outdated, we reserve the right to suspend or terminate your account and prohibit any and all current or future use of the Site or any portion thereof by you. During the registration process you will create a username and password. You are responsible for the confidentiality of your account and password and are fully responsible for all activities that occur under your account or password. You agree to immediately notify us of any unauthorized use of your account or password or any other security breach and to ensure that you exit from your account at the end of each session. You agree to be responsible for all charges resulting from the use of your account on the Site including charges resulting from unauthorized use of your account. We are not liable for any loss or damage resulting from your failure to comply with this section.</p>
				<p>You agree to use the Site for lawful purposes and that you are responsible for your use of and communications on the Site. You agree not to post on or transmit through the Site any unlawful, infringing, defamatory, obscene, indecent, threatening, offensive or otherwise objectionable material of any kind including any material that encourages illegal conduct or conduct that would encourage civil liability, infringe on other's intellectual property rights or otherwise violates any applicable local, state, national or international law. You agree not to use the Site in a manner that would interfere with normal operation or infringe on any others use of the Site.</p>
				<p>You agree not to access the Site by any means other than the interface we provide. Displaying or running the Site or any information or material displayed on the Site in frames or through similar means on another website without our prior authorization is prohibited. Any permitted links to the Site must comply with all applicable laws, rules and regulations.</p>
				<p>We make no representation that Materials contained on the Site or that herbal described on the Site are appropriate or available for use in jurisdictions outside the Sabah, or that this Agreement complies with the laws of any other country. Users of the Site outside the Sabah do so at their own initiative and risk and are responsible for complying with all applicable laws and regulations. You agree not to access the Site from any location or territory where its contents are illegal and that you and not us, are responsible for compliance with all applicable laws and regulations.</p>
				<p>This Agreement is effective until terminated by either us or you. We, in our sole discretion, may suspend or terminate this Agreement at any time without notice and deny you access to the Site or any portion of it. You may terminate this Agreement at any time by <a href="about.php">Contact Us</a> and discontinuing all use of the Site. Upon termination by us or you, you must destroy all materials obtained from the Site including all copies of such materials whether made under the terms of use contained in this Agreement or otherwise. We reserve the right to modify or discontinue, temporarily or permanently, the Site or any portion of it with or without notice. We are not liable to you or to any third party for any modification, suspension or discontinuation of the Site.</p>
				<p>We reserve the right to terminate any account if your order is deemed fraudulent or credit card charges are disputed. You agree that we may terminate or suspend your access to all or part of the Site, with or without notice, for any conduct that we, in our sole discretion, believes is in violation of any part of this Agreement, laws or regulations or is harmful to another user or us or our affiliates.</p>
				<p>The following shall survive any termination of the Agreement either by us or you; Privacy, Liability Disclaimer, Severability; Interpretation, and Miscellaneous.</p></br>

				<b><li id='user'>User Content and Conduct</li></b>
				<p>Where applicable at the Site, you may post your own content ("User Content"). You understand that you are solely responsible for any content you post to the Site. You alone assume all risks associated with your content including anyone's reliance on its accuracy, truthfulness or reliability or any disclosure by you of information in your content that makes you identifiable. Once published, your content may not be able to be withdrawn. You may not imply that your content is endorsed by us. You may expose yourself to liability if your content is false, defamatory, intentionally misleading, violates any third-party right including copyright, trademark, patent, trade secret, privacy right, right of publicity or any other intellectual property or proprietary right or is unlawful or violates or advocates the violation of any law or regulation. We cannot guarantee that your content will not be misused by other users. If you have information you want to keep confidential and/or do not want others to use, do not post it to the Site. We will not be liable for any user content, including, any errors or omissions, or any loss or damage incurred as the result of the use of any user content in any manner posted to the Site. We are not responsible for any user's use or misappropriation of any content you post to the Site.</p>
				<p>By posting user content to the Site, you hereby grant (or warrant that the owner of such rights has expressly granted) us perpetual, worldwide, royalty-free, irrevocable, non-exclusive right and license to use, host, store, reproduce, adapt, publish translate, edit, sub-license, modify, create derivative works from, communicate, publish, publicly display and distribute such content or incorporate such content into any form. The foregoing grant includes, without any limitation, any copyrights and other intellectual property rights in and to your user content. You represent and warrant that the content you posted does not violate the privacy or publicity rights, copyrights, contract rights or any other rights including moral rights of any person. You agree to pay for all royalties, fees and any other amounts owed to any person by reason of any content you posted to the Site. This license continues even if you stop using our Site.</p>
				<p>You understand that we may preserve user content and may disclose user content if required to do so by law or in good faith belief that such preservation or disclosure is reasonably necessary to comply with the legal process, enforce this Agreement, respond to claims that any user content violates the rights of third-parties, or protect the rights, property or personal safety of us, our users and the public. You understand that the technical processing and transmission of the Site, including your user content, may require transmitting over different networks and changes to conform to technical requirements of connecting 	devices or networks.</p>
				<p>Your content postings are voluntary including ideas, opinions and disclosures. There is no confidential or contractual relationship established by posting your content or review or use of your content. We are not liable for any disclosure of any user content including opinions or suggestions you post to the Site. We are entitled to unrestricted use of any user content it may receive, for any purpose, commercial or otherwise, without compensation to you as the content provider.</p>
				<p>You agree not to use the Site to:</p>
				<ol type="a">
					<li>Post or otherwise transmit any user content that is harmful, false, unlawful, obscene, defamatory or otherwise objectionable.</li>
					<li>Harass, stalk or otherwise abuse another.</li>
					<li>Impersonate any entity or misrepresent your affiliation with any person or entity.</li>
					<li>Harm minors.</li>
					<li>Attempt to disguise the origin of any user content posted to the Site.</li>
					<li>Post or otherwise transmit any user content that you do not have the right to transmit under any law, contractual or fiduciary relationships.</li>
					<li>Post or otherwise transmit any user content that infringes on any patent, copyright, trademark or other proprietary rights ("Rights") of any party or post or otherwise transmit any protected material on the Site.</li>
					<li>Post or otherwise transmit any unsolicited advertising, promotional materials, spam, junk mail, pyramid schemes or any other form of solicitation.</li>
					<li>Post or otherwise transmit any content that contains viruses, Trojan horses, or other harmful, disruptive or destructive materials that limit the functionality of any computer software, hardware or telecommunications equipment or interferes with any third party's use of the Site.</li>
					<li>Collect data about other Site users.</li>
					<li>Gain access to unauthorized areas of the Site including servers or networks.</li>
				</ol></br>
				<p>We will terminate the account and/or block Site users who violate the intellectual property rights of any person on the Site. You understand that by using the Site you may be exposed to other's user content that is indecent or otherwise objectionable. We do not endorse or have control over user content. User content is not reviewed by us prior to posting and does not reflect our opinions. We make no representations or warranties express or implied with regard to the accuracy or reliability of user content or any other material or information you may obtain from the Site. We are not responsible for monitoring the Site for inappropriate user content or conduct. If at any time we choose, in our sole discretion, to monitor the Site, we nonetheless assume no responsibility for the user content, have no obligation to modify or remove any inappropriate user content, and have no responsibility for the conduct of the Site users submitting any such user content. Notwithstanding the foregoing, we reserve the right to remove any user content that violates this Agreement or is otherwise objectionable, in our sole discretion. You agree that you must evaluate, and bear all the risks that are associated with the use of any user content, including reliance on accuracy, completeness or usefulness of such content. In this regard, you acknowledge you may not rely on any user content. You are solely responsible for your interactions with other Site users. We, in our sole discretion, have the right but are under no obligation to monitor communications between you and other Site users and to terminate your Site access.</p>
				<p>You agree to indemnify us for any and all third party claims, damages, losses, liability and causes of action in any way arising from or as a result of your posting any content or materials or your failure to comply with this Agreement. You agree to cooperate as fully as reasonably required in the defense of any claim. We reserve the right to assume the exclusive defense and control of any matter subject to indemnification by you, in which event you will still be required to indemnify us for the attorney fees and expenses in addition to any losses, claims, damages and liabilities incurred by us.</p>
				<p>We do not and cannot review all communications and content users post or upload to the interactive areas of the Site. We are not responsible for any of the content of these communications or materials posted or uploaded to the Site. We reserve the right to block, move, delete, edit in whole or in part, any content submitted by you to the Site that we determine to be fraudulent, deceptive, misleading, abusive, obscene, defamatory or a violation of a copyright, trademark or other intellectual property right of another or otherwise unacceptable to us in our sole discretion. Any content posted to interactive areas of the Site should not be construed as professional healthcare advice or instruction.</p></br>

				<b><li id='privacy'>Privacy Policy</li></b>
				<p>Your privacy and security are a top priority at SabahTCM. Since our inception in 2017, we have never rented, leased, or sold any customer information -- and never will.</p>
				<p>When you submit personal information on the Site you are consenting to the manner in which we will collect, use, disclose and otherwise manage your personal information, as set out below.</p>
				<ol type="a">
					<b><li>Collection and Use of Personal Information:</li></b>
					<p>We may collect personal information that you provide us when you: (a) exchange or request certain information about our products and services; (b) contact us; (c) visit or register with our Site or participate in another feature of our Site; (d) enter into a contest or sweepstakes or respond to one of our surveys; or (e) provide us with comments or suggestions. We take reasonable and appropriate steps to protect your personal information from unauthorized disclosure or access. However, no data transmitted over the Internet or stored on a server can ever be 100% secured. Therefore, while we strive to protect your privacy and personal information, we cannot guarantee the security of any information transmitted or disclosed to us online. We are not responsible for the disclosure, destruction or theft of your personal information. If you opted to register with us, you established a password for your account, in which case your online account information will be protected by your password. We suggest that you do not disclose your password to anyone. You are responsible for the confidentiality of your account and password and are fully responsible for all activities that occur under your account and password. We suggest creating challenging passwords such as those with alphanumeric combinations.</p>

					<b><li>Cookies:</li></b>
					<p>We utilize “cookies” which, if you allow their use, store small amounts of data on your computer when you visit the Site. Cookies assist us in tracking which of features of the Site you like best. Therefore, cookies enable us to customize our content according to your preferences. You have the ability to accept or decline cookies by modifying your browser settings. Our Site is viewable even if you disable the cookie function on your browser. However, if you disable cookies, main functionality like account login and checkout will not work..</p>
					<p>We may use cookies for a number of purposes, including but not limited to: keeping track of preferences you specify while you are using the Site; delivering advertisements and content relevant to your interests; providing general internal and customer analytics; maintaining information in both identifiable and anonymous forms; accessing your information when you "sign in" to provide you with customized content; conducting research to improve our content, products and services; supporting security measures such as requiring re-logging into the Site after a certain amount of time has elapsed; and assisting in identifying possible fraudulent activities.</p>
					<p>Part of this technology utilizes internet “cookies.” Cookies are stored on your hard drive in the form of a text file. Most cookies are “session cookies” meaning that are automatically deleted when you close your browser. Other cookies are called “persistent” because they do not expire. Typically these cookies allow us to provide targeting information about products and pricing. However you can easily remove them by following the directions in your browsers help file. While this statistical data is collected, it is important to note that we do not sell, rent or lease any of your personal information.</p>

					<b><li>SabahTCM & Third Parties:</li></b>
					<p>Like most retailers, as you visit our websites, we are collecting information about that visit. We collect this information to improve our delivery of information and services to you. In order to collect this information, we utilize technology from third party companies like Google. For example we utilize Google Analytics to aid in website measurement. This software is employed to evaluate – anonymously and in aggregate - how people use the SabahTCM of websites.</p>
					<p>This software provides information about your device (e.g. computer, tablet, smartphone), the type of browser (e.g. Chrome, Safari, Firefox) and operating system (e.g. Windows, Macintosh, Android, iOS). We gather this information to make sure the websites are optimized based on the technologies the majority of people are using to access our websites.</p>

					<b><li>Disclosures of Personal Information in Legal Proceedings:</li></b>
					<p>If we or any of our service providers is requested by law enforcement officials or judicial authorities to provide personal information on individual users, we or the applicable service provider may, without your consent, provide such information. In matters involving claims of personal or public safety, we or the applicable service provider may provide your personal information to appropriate authorities without your consent or court process. We or our service providers also will provide your personal information in response to a search warrant or other legally valid inquiry or order, or to an investigative body in the case of a breach of an agreement or contravention of law, or in litigation involving us, the applicable service provider, or otherwise as required by law. We may also disclose personal information to assist in debt collection where you owe a debt to us.</p>

					<b><li>Privacy Policy and Outside Links:</li></b>
					<p>This Privacy Policy only applies to the Site. Our Site may include links to the websites of our partners and advertisers. These other sites are outside of our control. Please be aware that these websites may collect information about you, and operate according to their own privacy practices which may differ from those contained in our Privacy Policy. Remember to consult that website's own privacy policy, as once you are outside the Site, any information you submit is no longer in our control.</p>

					<b><li>Privacy Policy Modifications:</li></b>
					<p>From time to time we may modify or amend this Privacy Policy in order to comply with new laws or regulations or to reflect future changes in our business practices. Any changes in our policies will be communicated in this page so please check back on occasion. We also may post a notice on our Site or send an email describing the changes.</p>
				</ol></br>

				<b><li id='disclaimer'>Liability Disclaimer</li></b>
				<p>YOU AGREE THAT THE USE OF THE SITE IS AT YOUR SOLE RISK. THE SITE AND THE MATERIALS CONTAINED HEREIN ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, EXCEPT AS OTHERWISE EXPRESSLY PROVIDED IN THIS AGREEMENT. SABAHTCM AND OTHER ADMIN AND OTHER REPRESENTATIVES, SUCCESSORS AND ASSIGNS OF ANY OF THEM (COLLECTIVELY, "SABAHTCM ENTITIES") EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
				<p>SABAHTCM ENTITIES MAKE NO WARRANTY THAT THE SITE WILL MEET YOUR REQUIREMENTS, THE SITE WILL BE TIMELY, SECURE, ERROR FREE OR UNINTERRUPTED, THE RESULTS OBTAINED FROM THE SITE WILL BE ACCURATE OR RELIABLE, THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL OBTAINED BY YOU THROUGH THE SITE WILL MEET YOUR EXPECTATIONS AND ANY SITE ERRORS WILL BE CORRECTED. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE SITE IS DONE AT YOUR OWN RISK AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY MATERIAL. NO INFORMATION OBTAINED BY YOU FROM SABAHTCM ENTITIES OR THROUGH THE SITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT.</p>
				<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SABAHTCM ENTITIES BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING OUT OF, IN CONNECTION WITH OR RELATING TO THE USE OF OR INABILITY TO USE THE SITE, INCLUDING ANY LIABILITY AS APUBLISHER OF INFORMATION, FOR ANY INCORRECT INFORMATION OR INACCURATE INFORMATION, FOR STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SITE OR FOR ANY OTHER MATTER RELATING TO THE SITE OR ANY THIRD PARTY WEBSITE. THIS IS A COMPREHENSIVE LIMITATION OF LIABILITY THAT APPLIES TO ALL DAMAGES OF ANY KIND, INCLUDING ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES (INCLUDING DAMAGES FOR LOSS OF GOOD WILL, LOSS OF USE, LOSS OF DATA, COST OF PROCURING SUBSTITUTE INFORMATION, LITIGATION OR THE LIKE), WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), INFORMATION LIABILITY OR OTHERWISE, EVEN IF SABAHTCM ENTITIES ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE LIMITATIONS OF LIABILITY SET FORTH SABAHTCM ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE ARRANGEMENT BETWEEN SABAHTCM AND YOU. THE INFORMATION OFFERED ON AND THROUGH THE SITE WOULD NOT BE PROVIDED WITHOUT SUCH LIMITATIONS. NOTWITHSTANDING THE FOREGOING, THE SOLE AND ENTIRE MAXIMUM LIABILITY OF SABAHTCM ENTITIES FOR ANY REASON, AND YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY CAUSE OR CLAIM WHATSOEVER, SHALL BE LIMITED TO THE AMOUNT PAID BY YOU FOR ANY INFORMATION FROM SABAHTCM ON THE SITE.</p>
				<p>BECAUSE SOME STATES AND/OR JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR CERTAIN TYPES OF DAMAGES, ACCORDINGLY, SOME OF THE ABOVE DISCLAIMERS AND LIMITATIONS MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SITE, OR WITH ANY OF THE TERMS OF USE CONTAINED IN THIS AGREEMENT, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE.</p></br>

				<b><li id='indem'>Indemnification</li></b>
				<p>You agree to indemnify, defend and hold harmless SabahTCM from and against all losses, expenses, costs and damages including attorney's fees resulting from your use of or contact on the Site, your use or your inability to use the Site or any Site postings or activity related to your account made by you or another person, your violation of any terms of this Agreement, your violation of any rights of a third party, or your violation of any applicable laws, rules or regulations. You agree to cooperate as fully as reasonably required in the defense of any claim. We reserve the right to assume the exclusive defense and control of any matter subject to indemnification by you, in which event you will still be required to indemnify us for the attorney fees and expenses in addition to any losses, claims, damages and liabilities incurred by us. You shall not in any event settle any matter without prior written consent of SabahTCM.</p></br>

				<b><li id='cr'>Copyright, Trademarks and other Intellectual Property</li></b>
				<p>You acknowledge that all materials on the Site the Reviews and Rewards Programs, including the Site’s design, text, graphics, sounds, pictures, software and other files and the selection and arrangement thereof, (collectively, "Materials"), are our property and are subject to and protected by United States and international copyright and other intellectual property laws and rights. The trademarks, service marks, trade names, and logos (collectively, "Marks") contained on the Site, including without limitation SabahTCM® are the sole property of SabahTCM and may not be copied or otherwise used, in whole or in part without the prior written authorization of SabahTCM. In addition all page headers, custom graphics and custom icons are Marks of SabahTCM and may not be copied or otherwise used, in whole or in part without the prior written authorization of SabahTCM. Other copyrights, trademarks, product names, company names, logos or intellectual property are the property of the respective owners with all rights reserved. Any use of any Materials or Marks owned by SabahTCM is considered an infringement or our intellectual property rights (including patent rights) and will be legally pursued as such.</p>
				<p>By agreeing to the terms of use contained in this Agreement, you agree that you will not use any text, photos, likenesses or other copyrighted or protected material of SabahTCM or of other third parties without the prior express written consent of SabahTCM.</p></br>

				<b><li id='agree'>Agreement</li></b>
				<p>This Agreement constitutes the only Agreement between us and you with respect to the subject matter of this Agreement. This Agreement supersedes all prior or contemporaneous Agreements, representations, warranties and understandings, written or oral, with respect to the subject matter of this Agreement.</p></br>

				<b><li id='sever'>Severability; Interpretation</li></b>
				<p>If any provision of this Agreement is deemed void, unlawful, or otherwise unenforceable for any reason, that provision will be severed from this Agreement and the remainder of this Agreement will remain in force. When used in this Agreement, the term "including" will be deemed to be followed by the words "without limitation".</p></br>

				<b><li id='mis'>Miscellaneous</li></b>
				<p>You may not assign this Agreement, by operation of law or otherwise, without our prior written consent. Subject to that restriction, this Agreement will be binding on, inure of the benefit of and be enforceable against the parties and their respective successors and assigns.</p>
				<p>The failure of the SabahTCM to enforce your strict performance of any term of this Agreement will not constitute a waiver of such term and will not be considered a waiver or limit that party's right thereafter to insist upon strict adherence to that term or any other term of this Agreement. You agree that regardless of any statute or law to the contrary, any claim of cause of action arising from or relating to the use of the Site or this Agreement must be filed within one (1) year after such claim or cause of action arose or will be permanently barred. The "Liability Disclaimer" provisions of this Agreement are for the benefit of SabahTCM Entities as defined herein, and each of these individuals or entities shall have the right to assert and enforce these provisions directly against your on its own behalf.</p></br>

				<b><li id='cu'>Contact Us</li></b>
				<p>If you have any questions about this Agreement, <a href="about.php">Contact Us</a>.</p>
			</ol>
		</div>
	</div>
	<?php
		include ("footer.php");
	?>
</body>
</html>